kind: pipeline
type: docker
name: default

steps:
- name: build
  image: alpine:latest
  volumes:
  - name: project_dir
    path: /nerd_build
  commands:
  - apk add --update --no-cache go
  - mkdir -p /nerd_build/usr/bin
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o /nerd_build/usr/bin/hello main.go


- name: make rpm
  image: alpine:latest
  environment:
    ARCH: x86_64
    VERSION: 1.1.1
    TS: timestamp
    NAME: nerd-build
    PACKAGE_TYPE: rpm
    TO: -1001184051909
    TG_TOKEN:
      from_secret: tg_token
  volumes:
  - name: project_dir
    path: /nerd_build
  commands:
  - apk add --update --no-cache rpm ruby curl && gem install fpm
  - fpm -s dir -t $${PACKAGE_TYPE} -p /nerd_build/$${NAME}-$${TS}-$${VERSION}.$${ARCH}.$${PACKAGE_TYPE} -n $${NAME} -v $${VERSION}-a $${ARCH} -C /nerd_build .
  - |
     curl -s "https://api.telegram.org/bot$${TG_TOKEN}/sendDocument" \
        -F chat_id="$${TO}" \
        -F parse_mode="HTML" \
        -F document=@"/nerd_build/$${NAME}-$${TS}-$${VERSION}.$${ARCH}.$${PACKAGE_TYPE}"

  
- name: pull
  image: alpine:3.15
  environment:
    TG_TOKEN:
      from_secret: tg_token
    TO: -1001184051909
  volumes:
  - name: temp
    path: /foo
  commands:
  - apk add --update --no-cache curl
  - |
     curl -s "https://api.telegram.org/bot$${TG_TOKEN}/sendDocument" \
        -F chat_id="$${TO}" \
        -F parse_mode="HTML" \
        -F document=@"/foo/nerd-build-timestamp-1.1.1.x86_64.rpm"
    
  

volumes:
- name: temp
  host:
    path: /home/nikitin_i/drone/temp
