kind: pipeline
type: docker
name: default

environment:
  ROOT_DIR: "/tmp/"
  HOME_DIR: nerd_builder
  TEMP: temp

steps:

- name: make structure
  image: alpine:3.15
  volumes:
  - name: test
    path:  /tmp/
  commands:
  - |
    mkdir -p "/tmp/$${HOME_DIR}/src/usr/bin/" \
             "/tmp/$${HOME_DIR}/src/usr/share/" \
             "/tmp/$${HOME_DIR}/$${TEMP}" \
             "/tmp/$${HOME_DIR}/output"

        
- name: micro install
  image: alpine:3.15
  volumes:
  - name: test
    path:  /tmp/
  commands:
  - apk add --update --no-cache curl bash
  - curl https://getmic.ro | bash
  #- mv $(which micro) "/tmp/$${HOME_DIR}/src/usr/bin/nerdmicro"
  - mv ./micro "/tmp/$${HOME_DIR}/src/usr/bin/nerdmicro"
  depends_on:
  - make structure

volumes:
- name: builder_dir
  host:
    path: /root/

- name: test
  temp: {}

- name: docker-socket
  host:
    path: /var/run/docker.sock

- name: docker-plugins
  host:
    path: /var/lib/docker/plugins/
