kind: pipeline
type: docker
name: default

environment:
  BUILDER: "/nerd_builder/"
  TEMP: temp

steps:

- name: make structure
  image: alpine:3.15
  volumes:
  - name: builder
    path:  $${BUILDER}
  commands:
  - |
    mkdir -p "/$${BUILDER}/src/usr/bin/" \
             "$${BUILDER}/src/usr/share/" \
             "$${BUILDER}/$${TEMP}" \
             "$${BUILDER}/output"

        
- name: micro install
  image: alpine:3.15
  volumes:
  - name: builder
    path:  $${BUILDER}
  commands:
  - apk add --update --no-cache curl bash
  - curl https://getmic.ro | bash
  #- mv $(which micro) "/tmp/$${HOME_DIR}/src/usr/bin/nerdmicro"
  - mv ./micro "$${BUILDER}/src/usr/bin/nerdmicro"
  depends_on:
  - make structure

volumes:
- name: builder_dir
  host:
    path: /root/

- name: builder
  temp: {}

- name: docker-socket
  host:
    path: /var/run/docker.sock

- name: docker-plugins
  host:
    path: /var/lib/docker/plugins/
