kind: pipeline
type: docker
name: default

environment:
  HOME_DIR: nerd_build

steps:
- name: build bin
  image: alpine:latest
  volumes:
  - name: temp
    path: /tmp
  commands:
  #- rm -r /tmp/${HOME_DIR}/*
  - apk add --update --no-cache go
  - mkdir -p "/tmp/$${HOME_DIR}/usr/bin"
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o "/tmp/$${HOME_DIR}/usr/bin/hello" main.go

- name: make pkg
  image: alpine:latest
  environment:
    ARCH: x86_64
    RELEASE: 1.1.1
    VERSION: timestamp
    NAME: nerd-build
    PACKAGE_TYPE: rpm
    TG_TOKEN:
      from_secret: tg_token
  volumes:
  - name: temp
    path: /tmp
  commands:
  - apk add --update --no-cache ruby && gem install fpm
  - |
    if [ "$PACKAGE_TYPE" = "rpm" ]; then \
        apk add --no-cache rpm; \
    elif [ "$PACKAGE_TYPE" = "deb" ]; then \
        apk add --no-cache binutils tar; \
    fi
  - | 
    fpm -s dir -t $${PACKAGE_TYPE} \
        -p "/tmp/$${HOME_DIR}/$${NAME}-$${VERSION}-$${RELEASE}.$${ARCH}.$${PACKAGE_TYPE}" \
        -n "$${NAME}" \
        -v "$${RELEASE}" \
        -a "$${ARCH}" \
        -C "/tmp/$${HOME_DIR}" .
        
  - echo "/tmp/$${HOME_DIR}/$${NAME}-$${TS}-$${VERSION}.$${ARCH}.$${PACKAGE_TYPE}" > /tmp/nerd_build/path.txt
  depends_on:
  - build bin

  
- name: pull
  image: alpine:3.15
  environment:
    TG_TOKEN:
      from_secret: tg_token
    TO: -1001184051909
  volumes:
  - name: temp
    path: /tmp
  commands:
  - export PATH_FILE=$(cat "/tmp/$${HOME_DIR}/path.txt") 
  - apk add --update --no-cache curl
  - |
     curl -s "https://api.telegram.org/bot$${TG_TOKEN}/sendDocument" \
        -F chat_id="$${TO}" \
        -F parse_mode="HTML" \
        -F document=@$${PATH_FILE}
  depends_on:
  - make pkg
        
    
  

volumes:
- name: temp
  host:
    path: /tmp
