kind: pipeline
type: docker
name: default

environment:
  HOME_DIR: nerd_build

steps:

- name: prepared loki
  image: alpine:latest
  environment:
    VERSION: 2.7.0
  volumes:
  - name: temp
    path: /tmp
  - name: docker-socket
    path: /var/run/docker.sock
  - name: docker-plugins
    path: /var/lib/docker/plugins/
  privileged: true
  commands:
  - apk add --update --no-cache docker jq
  #- docker plugin install "grafana/loki-docker-driver:$${VERSION}" --grant-all-permissions

  - ls -l /var/lib/docker/plugins/
  - | 
    loki_id=$(docker plugin ls | awk '/Loki Logging Driver/ {print $1}')
      if [ -n "$loki_id" ]; then
      # Запустить команду docker plugin inspect с полученным ID
        inspect_result=$(docker plugin inspect --format '{{json .}}' "$loki_id")

      # Извлечь значение ключа "Id" из результирующего JSON
        loki_plugin_id=$(echo "$inspect_result" | jq -r '.Id')

        #cp -r "/var/lib/docker/plugins/$${loki_plugin_id}/rootfs" ./
        #cp "/var/lib/docker/plugins/$${loki_plugin_id}/config.json" ./
        
        #rm -i "/var/lib/docker/plugins/$${loki_plugin_id}/rootfs/var/run"
        #cat "/var/lib/docker/plugins/$${loki_plugin_id}/config.json"
        cat "/var/lib/docker/plugins/$${loki_plugin_id}/config.json" | jq .plugin.Config > /tmp/new_file.json
        
      else
        echo "Loki Logging Driver not found."
      fi

      

      

- name: build bin
  image: alpine:latest
  volumes:
  - name: temp
    path: /tmp
  commands:
  - rm -rf "/tmp/$${HOME_DIR}/"
  - apk add --update --no-cache go
  - mkdir -p "/tmp/$${HOME_DIR}/usr/bin"
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o "/tmp/$${HOME_DIR}/usr/bin/hello" main.go
  depends_on:
  - prepared loki


- name: make pkg
  image: alpine:latest
  environment:
    TZ: Europe/Moscow
    ARCH: x86_64
    RELEASE: 1.1.1
    NAME: nerd-build
    PKG: rpm
  volumes:
  - name: temp
    path: /tmp
  commands:
  - apk add --no-cache ruby tzdata && gem install fpm
  - |
    if [ "$PKG" = "rpm" ]; then \
        apk add --no-cache rpm; \
    elif [ "$PKG" = "deb" ]; then \
        apk add --no-cache binutils tar; \
    fi
  - export VERSION=$(TZ=$${TZ} date +'%Y%m%dT%H%M%S')
  - export PATH_FILE="/tmp/$${HOME_DIR}/$${NAME}-$${VERSION}-$${RELEASE}.$${ARCH}.$${PKG}"
  - | 
    fpm -s dir -t $${PKG} \
        -p "$${PATH_FILE}" \
        -n "$${NAME}" \
        -v "$${RELEASE}" \
        -a "$${ARCH}" \
        -C "/tmp/$${HOME_DIR}" .
  - echo "$${PATH_FILE}" > "/tmp/$${HOME_DIR}/path.txt"
  depends_on:
  - build bin

  
- name: pull
  image: alpine:3.15
  environment:
    TG_TOKEN:
      from_secret: tg_token
    TO: -1001184051909
  volumes:
  - name: temp
    path: /tmp
  commands:
  - export PATH_FILE=$(cat "/tmp/$${HOME_DIR}/path.txt") 
  - apk add --update --no-cache curl
  - |
     curl -s "https://api.telegram.org/bot$${TG_TOKEN}/sendDocument" \
        -F chat_id="$${TO}" \
        -F parse_mode="HTML" \
        -F document=@$${PATH_FILE}
  depends_on:
  - make pkg
        
    
  

volumes:
- name: temp
  host:
    path: /tmp

- name: docker-socket
  host:
    path: /var/run/docker.sock

- name: docker-plugins
  host:
    path: /var/lib/docker/plugins/
