kind: pipeline
type: docker
name: default

steps:
- name: build
  image: alpine:3.15
  volumes:
  - name: temp
    path: /foo
  commands:
  - apk add --update --no-cache go=1.17
  - go build -o hello main.go
  - cp hello /foo/hello

- name: pull
  image: alpine:3.15
  environment:
    TG_TOKEN:
      from_secret: tg_token
    TO: -1001180112580
  volumes:
  - name: temp
    path: /foo
  commands:
  - apk add --update --no-cache curl
  - |
     curl -s "https://api.telegram.org/bot$${TG_TOKEN}/sendDocument" \
        -F chat_id="$${TO}" \
        -F parse_mode="HTML" \
        -F document=@"/foo/hello"
    
  

volumes:
- name: temp
  host:
    path: /home/nikitin_i/drone/temp
