kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.22-rc-alpine
  volumes:
  - name: temp
    path: /foo
  commands:
  - env CGO_ENABLED=0 go build -o hello main.go
  - cp hello /foo/hello

- name: make rpm
  image: oraclelinux:9-slim
  volumes:
  - name: temp
    path: /foo
  commands:
  - microdnf -y update && microdnf -y install rpm-build squashfs-tools ruby && microdnf -y clean all && gem install fpm
  - mkdir -p /home/nerd-build/usr/bin
  - cp /foo/hello /home/nerd-build/usr/bin


  
- name: pull
  image: alpine:3.15
  environment:
    TG_TOKEN:
      from_secret: tg_token
    TO: -1001184051909
  volumes:
  - name: temp
    path: /foo
  commands:
  - apk add --update --no-cache curl
  - |
     curl -s "https://api.telegram.org/bot$${TG_TOKEN}/sendDocument" \
        -F chat_id="$${TO}" \
        -F parse_mode="HTML" \
        -F document=@"/foo/nerd-build-1488-1.1.1.x86_64.rpm"
    
  

volumes:
- name: temp
  host:
    path: /home/nikitin_i/drone/temp
