kind: pipeline
type: docker
name: default

environment:
  BIN_DIR: "/nerd_builder/src/usr/bin/"
  SHARE_DIR: "/nerd_builder/src/usr/share/"
  TEMP_DIR: "/nerd_builder/temp"
  OUTPUT_DIR: "/nerd_builder/output"

steps:


- name: micro install
  image: alpine:3.15
  volumes:
  - name: builder
    path:  /nerd_builder/
  commands:
  - apk add --update --no-cache curl bash
  - curl https://getmic.ro | bash
  #- mv $(which micro) "/tmp/$${HOME_DIR}/src/usr/bin/nerdmicro"
  - mv ./micro "$${BIN_DIR}/nerdmicro"


#volumes:
#- name: builder_dir
#  host:
#    path: /root/

- name: builder
  temp: {}

- name: docker-socket
  host:
    path: /var/run/docker.sock

- name: docker-plugins
  host:
    path: /var/lib/docker/plugins/
