kind: pipeline
type: docker
name: default

steps:
- name: hello_word
  image: golang:1.21.5-alpine3.19
  commands:
  - go build -o hello main.go
  - docker cp $(docker ps -q -n=1):hello /home/nikitin_i/drone/temp
