kind: pipeline
type: docker
name: default

environment:
  BIN_DIR: "/nerd_builder/src/usr/bin/"
  SHARE_DIR: "/nerd_builder/src/usr/share/"
  TEMP_DIR: "/nerd_builder/temp"
  OUTPUT_DIR: "/nerd_builder/output"

steps:

- name: make structure
  image: alpine:3.15
  volumes:
  - name: builder
    path:  /nerd_builder/
  commands:
  - |
    mkdir -p "$${BIN_DIR}" \
             "$${SHARE_DIR}" \
             "$${TEMP_DIR}" \
             "$${OUTPUT_DIR}"



- name: builder
  temp: {}

- name: docker-socket
  host:
    path: /var/run/docker.sock

- name: docker-plugins
  host:
    path: /var/lib/docker/plugins/
