kind: pipeline
type: docker
name: default

steps:
- name: build
  image: alpine:latest
  volumes:
  - name: temp
    path: /foo
  commands:
  - apk add --update --no-cache go
  - env CGO_ENABLED=0 go build -o hello main.go
  - cp hello /foo/hello

- name: make rpm
  image: fedora:latest
  volumes:
  - name: temp
    path: /foo
  commands:
  - dnf -y update
  - dnf install  -y https://github.com/genereese/togo/releases/download/v3.0r5/togo-3.0-5.noarch.rpm python-pip
  - pip install SQLObject
  - cd ~
  - togo project create nerd-build && sed -i 's/BuildArch: noarch/BuildArch: x86_64/' nerd-build/spec/headers && cd nerd-build && mkdir -p root/usr/local/bin && cp /foo/hello root/usr/local/bin/
  - togo build package
  
- name: pull
  image: alpine:3.15
  environment:
    TG_TOKEN:
      from_secret: tg_token
    TO: -1001184051909
  volumes:
  - name: temp
    path: /foo
  commands:
  - apk add --update --no-cache curl
  - |
     curl -s "https://api.telegram.org/bot$${TG_TOKEN}/sendDocument" \
        -F chat_id="$${TO}" \
        -F parse_mode="HTML" \
        -F document=@"/foo/hello"
    
  

volumes:
- name: temp
  host:
    path: /home/nikitin_i/drone/temp
